engines:
  eslint:
    enabled: true
  tslint:
    enabled: true
    channel: beta
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
ratings:
  paths:
    - "src/**/*"
exclude_paths:
- "docs/"
- "dist/"